"""Add profile_picture of actor, original_poster and original_time of boost

Revision ID: 17d8f1d6287c
Revises: 80ed3db69806
Create Date: 2023-04-24 19:05:09.496545

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '17d8f1d6287c'
down_revision = '80ed3db69806'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('boosts', sa.Column('original_poster_id', sa.Integer(), nullable=True))
    op.add_column('boosts', sa.Column('original_time', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'boosts', 'actors', ['original_poster_id'], ['id'])
    op.create_unique_constraint(None, 'settings', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settings', type_='unique')
    op.drop_constraint(None, 'boosts', type_='foreignkey')
    op.drop_column('boosts', 'original_time')
    op.drop_column('boosts', 'original_poster_id')
    op.drop_column('actors', 'profile_picture')
    # ### end Alembic commands ###
