"""Add in_reply_to and replies

Revision ID: 4f9f5c7c20b3
Revises: 17d8f1d6287c
Create Date: 2023-04-25 11:21:26.850173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4f9f5c7c20b3'
down_revision = '17d8f1d6287c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boosts', sa.Column('in_reply_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'boosts', 'boosts', ['in_reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'boosts', type_='foreignkey')
    op.drop_column('boosts', 'in_reply_to_id')
    # ### end Alembic commands ###
