"""Change name of fields and add creator of group

Revision ID: e85d4e547af4
Revises: 4f9f5c7c20b3
Create Date: 2023-05-15 18:12:25.509246

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'e85d4e547af4'
down_revision = '4f9f5c7c20b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'summary', nullable=False, new_column_name='description')
    op.alter_column('groups', 'icon', nullable=False, new_column_name='profile_picture')
    op.alter_column('groups', 'preferredUsername', nullable=False, new_column_name='display_name')
    op.alter_column('groups', 'image', nullable=False, new_column_name='cover_photo')

    op.add_column('groups', sa.Column('creator_id', sa.Integer(), nullable=True))
    creator_id = table('groups', column('creator_id'))
    op.execute(creator_id.update().values(creator_id=1))
    op.alter_column('groups', 'creator_id', nullable=False)
    op.create_foreign_key(None, 'groups', 'actors', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'description', nullable=False, new_column_name='summary')
    op.alter_column('groups', 'profile_picture', nullable=False, new_column_name='icon')
    op.alter_column('groups', 'display_name', nullable=False, new_column_name='preferredUsername')
    op.alter_column('groups', 'cover_photo', nullable=False, new_column_name='image')
    # op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'creator_id')
    # ### end Alembic commands ###
